sudo: false
language: node_js
node_js:
  - '4'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      # for opc simulator:
      - mesa-common-dev
      - freeglut3-dev

before_script:
  - npm prune
  - git submodule update --init --recursive && npm run -s build-opc && npm run opc-dummy & sleep 15
  # - cd www && npm i && npm -s build && cd .. # not tested atm
before_install:
  - npm i -g npm@^2.0.0
after_success:
  - npm -s run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
