---
colors:
  red: "hsla(0, 100%, 59%, 1)"
  yellow: "hsla(59, 100%, 56%, 1)"
  green: "hsla(111, 100%, 60%, 1)"
  cyan: "hsla(171, 100%, 54%, 1)"
  blue: "hsla(239, 100%, 60%, 1)"
  purple: "hsla(276, 100%, 60%, 1)"
  pink: "hsla(322, 100%, 59%, 1)"
  white: "#ccc"
connection:
  host: localhost
  port: 7890

# TODO: adress individual fadecandy strips and loose the spacers.
# or: better config in pixelwall server?
sections:
  - id: first_box # top left
    description: Franco CI status
    strip: 1
    length: 60
    # request: http://medienarchiv.zhdk.ch
    # expect:
    #   status:
    #     gte: 200
    #     lt: 300
    #   output:
    #     contains: "Digitales Areal ZHdK"
    request: x
    expect: {}
    ok: green
    fail: red

  - {id: first_box_spacer, length: 4,
    request: x, expect: {}, ok: black}

  - id: second_box # top right
    description: Tom CI status
    strip: 2
    length: 60
    request: x
    expect: {}
    ok: green
    fail: red

  - {id: second_box_spacer, length: 4,
    request: x, expect: {}, ok: black}

  - id: third_box # bottom left
    description: "Matus CI status"
    length: 60
    request: x
    expect: {}
    ok: green
    fail: red

  - {id: third_box_spacer, length: 4,
    request: x, expect: {}, ok: black}

  - id: fourth_box # bottom right
    description: "Max CI status"
    length: 120
    request: x
    expect: {}
    ok: green
    fail: red

  - {id: fourth_box_spacer, length: 4,
    request: x, expect: {}, ok: black}
