---
# colors:
#   green: green
#   red: red
#   white: "#ccc"
# connection:
#   host: localhost
#   port: 7890

# TODO: adress individual fadecandy strips and loose the spacers.
# or: better config in pixelwall server?
sections:
  - id: first_box # top left
    description: HTTP GET medienarchiv.zhdk.ch
    strip: 1
    length: 60
    request: http://medienarchiv.zhdk.ch
    expect:
      status:
        gte: 200
        lt: 300
      output:
        contains: "Digitales Areal ZHdK"
    ok: green
    fail: red
  - id: first_box_unadressed # spacer
    length: 4

  - id: second_box # top right
    description: Madek 3 Tests
    strip: 2
    length: 60
    ok: green
    fail: red
  - id: second_box_unadressed # spacer
    length: 4

  - id: third_box # bottom left
    description: "TODO"
    length: 60
    ok: green
    fail: red
  - id: third_box_unadressed # spacer
    length: 4

  - id: fourth_box # bottom right
    description: Madek v3 
    length: 120
    ok: green
    fail: red
  - id: fourth_box_unadressed # spacer
    length: 4
